minimum_pre_commit_version: 2.20.0
default_stages: [commit, push]
exclude: "^$"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: end-of-file-fixer
        files: \.(py|sh|rst|yml|yaml)$
      - id: mixed-line-ending
      - id: trailing-whitespace
        files: \.(py|sh|rst|yml|yaml)$

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        args:
          - --config=pyproject.toml
          - --ignore=E203,E266,E501,W503,F403,F401,B905, D102
        additional_dependencies:
          [
            "flake8-blind-except",
            "flake8-docstrings",
            "flake8-bugbear",
            "flake8-comprehensions",
            "flake8-docstrings",
            "flake8-implicit-str-concat",
            "flake8-comments",
            "pydocstyle>=5.0.0",
          ]
        # exclude: ^scalingup/(prompts|policy/prompts|task_generator/prompts)/|build/|scripts/|scalingup/algo/robomimic_nets|scalingup/algo/tsdf
  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.0
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args:
          - "--check"
          - "--no-update"
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: "v1.4.1"
  #   hooks:
  #     - id: mypy
  #       args:
  #         - --check-untyped-defs
  #       additional_dependencies:
  #         - "pydantic"
  #       exclude: ^scalingup/(prompts)/|tests/|build
  # - repo: https://github.com/codespell-project/codespell
  #   rev: v2.2.5
  #   hooks:
  #     - id: codespell
  #       args:
  #         - -L caler
  #         - --write
  #       exclude: scripts/visualizations/rollout|presentation/js|presentation/plugin|presentation/package-lock.json|.svg|presentation/index.html|scalingup/algo/tsdf.py
