hydra:
  run:
    dir: runs/outputs/train/${now:%Y-%m-%d}/${now:%H-%M-%S}_${hydra.job.name}
  job:
    name: default

device: cuda
use_amp: false
resume: false
seed: 10000

env:
  task: pusht
  sparse_reward: false
  agent_pos_dim: 2
  fps: 10


data_generation:
  episode_length: 100
  num_episodes: 10
  get_block_poses: true
  enrich_data: true
  get_original_goal: false
  conditioning: "achieved_goal"
  goal_map_vis: aggregated
  # expert_data: true

delta_timestamps:
  observation_image: "[i / ${env.fps} for i in range(1 - ${model.obs_horizon}, 1)]"
  observation_state: "[i / ${env.fps} for i in range(1 - ${model.obs_horizon}, 1)]"
  action: "[i / ${env.fps} for i in range(1 - ${model.obs_horizon}, 1 - ${model.obs_horizon} + ${model.pred_horizon})]"


training:
  policy_refinement: 30
  num_epochs: 20
  batch_size: 128
  num_workers: 4
  log_interval: 20

optim:
  name: adam
  lr: 1.0e-4
  betas: [0.95, 0.999]
  eps: 1.0e-8
  weight_decay: 1.0e-6
  grad_clip_norm: 10.0
  scheduler:
    name: cosine
    num_warmup_steps: 500

model:
  vision_encoder:
    name: "resnet18"
    feature_dim: 512
  obs_horizon: 2
  pred_horizon: 16
  action_horizon: 8
  action_dim: 2

diffusion:
  scheduler: "DDIM"
  num_diffusion_iters_train: 50
  num_diffusion_iters_eval: 5
  beta_schedule: "squaredcos_cap_v2"
  beta_start: 0.0001
  beta_end: 0.02
  clip_sample: true
  clip_sample_range: 1.0
  prediction_type: "epsilon"

save_model: false

evaluation:
  eval: true
  intermediate_goals: false
  num_episodes: 30
  max_steps: 200
  save_video: true

wandb:
  enable: true
  disable_artifact: true
  project: GCDP
