hydra:
  run:
    dir: runs/outputs/train/${now:%Y-%m-%d}/${now:%H-%M-%S}_${hydra.job.name}
  job:
    name: ???

device: cuda
use_amp: false
resume: false
seed: 1000

env:
  task: pusht
  sparse_reward: false
  agent_pos_dim: 2
  fps: 10


data_generation:
  episode_length: 100
  num_episodes: 20
  get_block_poses: true
  enrich_data: true
  get_original_goal: false
  conditioning: "achieved_goal"
  goal_map_vis: aggregated
  # expert_data: true

expert_data:
  num_episodes: 30
  transitions: "random" # "subsequent", "terminal", "evenly_spaced", "random", "beta"
  subsequent_steps: 32 # for "subsequent" goal transitions
  num_goals: 30 # for "evenly_spaced", "random" and "beta" goal transitions
  dataset_id: "lerobot/pusht"


delta_timestamps:
  observation_image: "[i / ${env.fps} for i in range(1 - ${model.obs_horizon}, 1)]"
  observation_state: "[i / ${env.fps} for i in range(1 - ${model.obs_horizon}, 1)]"
  action: "[i / ${env.fps} for i in range(1 - ${model.obs_horizon}, 1 - ${model.obs_horizon} + ${model.pred_horizon})]"


training:
  policy_refinement: 100
  num_epochs: 5
  batch_size: 256
  num_workers: 0
  log_interval: 40

optim:
  name: adam
  lr: 1.0e-4
  betas: [0.95, 0.999]
  eps: 1.0e-8
  weight_decay: 1.0e-6
  grad_clip_norm: 10.0
  scheduler:
    name: cosine
    num_warmup_steps: 500

model:
  goal_conditioned: true
  vision_encoder:
    name: "resnet18" # resnet18, resnet34, resnet50
    # feature_dim: 64
    weights: null # "IMAGENET1K_V1", null
    crop_shape: [84, 84]
    crop_is_random: true
    use_group_norm: true
    spatial_softmax_num_keypoints: 32
  input_shapes:
    observation.image: [3, 96, 96]
    # observation.state: [${env.agent_pos_dim}]
    # action: [${model.action_dim}]
  obs_horizon: 2
  pred_horizon: 16
  action_horizon: 8
  action_dim: 2

diffusion:
  scheduler: "DDIM"
  num_diffusion_iters_train: 100
  num_diffusion_iters_eval: 10
  beta_schedule: "squaredcos_cap_v2"
  beta_start: 0.0001
  beta_end: 0.02
  clip_sample: true
  clip_sample_range: 1.0
  prediction_type: "epsilon"

save_model: true

evaluation:
  eval: true
  intermediate_goals: false
  num_episodes: 30
  max_steps: 300
  progressive_goals: false
  save_video: true
  save_progressive_goals: false

wandb:
  enable: true
  disable_artifact: true
  project: GCDP_Exploration


eval_generalisation:
  num_episodes: 30
  max_steps: 300
  save_video: true
